backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
              label: Hero Section,
              name: hero,
              widget: object,
              fields: [
                # {label: Background Image (mobile only), name: background_image, widget: image},
                {label: Logo, name: image, widget: image},
                {label: Title, name: title, widget: string},
                {label: Subtitle, name: subtitle, widget: string},
              ]
            }
          - label: Affiliate_logos
            name: affiliate_logos
            widget: object
            fields:
            - label: Images
              name: images
              widget: list
              fields:
              - label: Image
                name: image
                widget: image
          - {
              label: Mission Section,
              name: mission,
              widget: object,
              fields: [
                {label: Title, name: title, widget: string},
                {label: Mission Statement, name: statement, widget: text},
                {label: Image, name: image, widget: image}
              ]
            }
          - {
              label: Current Projects Section,
              name: current_projects,
              widget: object,
              fields: [
                {label: Subtitle, name: subtitle, widget: string},
                {label: Title, name: title, widget: string},
                {
                  label: Spotlight Project,
                  name: spotlight_project,
                  widget: object,
                  fields: [
                    {label: Side Image, name: side_image, widget: image},
                    {label: Project Logo, name: logo, widget: image},
                    {label: Title, name: title, widget: string},
                    {label: Subtitle, name: subtitle, widget: string},
                    {label: Description, name: description, widget: text},
                    {label: Button Text, name: button_text, widget: string},
                    {label: Button Link, name: button_link, widget: string}
                  ]
                },
                {label: Banner Text, name: banner_text, widget: string}
              ]
            }
          - label: Past Projects
            name: past_projects
            widget: list
            fields:
              - label: Project
                name: project
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Description, name: description, widget: text}
                  - {label: Image, name: image, widget: image}