backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {
              label: Hero Section,
              name: hero,
              widget: object,
              fields: [
                {label: Background Image (mobile only), name: background_image, widget: image},
                {label: Logo, name: image, widget: image},
                {label: Title, name: title, widget: string},
                {label: Subtitle, name: subtitle, widget: string},
              ]
            }
          - label: Affiliates Section
            name: affiliates
            widget: object
            fields:
            - label: Affiliate_logos
              name: affiliate_logos
              widget: object
              fields:
              - label: Images
                name: images
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
